
import { Header } from '@/components/page/header';

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background font-body">
      <Header />
      <main className="flex-1">
        <div className="py-12 md:py-20 px-4 border-b">
           <h2 className="text-4xl sm:text-5xl md:text-6xl font-black font-headline mb-4 text-foreground tracking-tight text-center">
             Terms of Service
           </h2>
           <p className="text-lg text-muted-foreground max-w-2xl mx-auto text-center">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
           </p>
        </div>
        
        <div className="max-w-4xl mx-auto px-4 sm:px-8 py-12 md:py-20">
            <div className="prose prose-lg prose-invert mx-auto text-muted-foreground">
                <h3 className="text-foreground">Acceptance of Terms</h3>
                <p>By using BizIdeaSpark (“we”, “our”, “us”), you agree to these Terms of Service. If you do not agree, please do not use the website.</p>

                <h3 className="text-foreground">Use of the Service</h3>
                <p>BizIdeaSpark provides AI-generated business ideas and summaries for informational and educational purposes only. You are responsible for how you use the information generated by the site.</p>

                <h3 className="text-foreground">No Guarantees</h3>
                <p>We make no guarantees about the accuracy, completeness, or suitability of the ideas and content provided. All content is provided “as is,” without warranties of any kind.</p>

                <h3 className="text-foreground">Limitation of Liability</h3>
                <p>BizIdeaSpark is not responsible for any losses, damages, or issues that arise from using the site or relying on the content generated.</p>

                <h3 className="text-foreground">Changes to the Terms</h3>
                <p>We may update these Terms from time to time. Continued use of the website means you accept the updated Terms.</p>
            </div>
        </div>
      </main>
    </div>
  );
}
